Repository youcan-shop/cod-theme-2, pull requests merged in 2023-05, with the labels that each got.

#51 DARK : COD V2 > remove unused file
  theme_31-3-2023.zip
Labels: Ready for review

#52 Section initial background color is not getting applied
  package.json
  sections/feature-products-by-category.liquid
  templates/index.json
Labels: Ready for review

#53 YSHOP2-418: Wording update for section/blocks settings
  sections/feature-products-by-category.liquid
  templates/index.json
Labels: enhancement, Ready for review

#54 YSHOP2-364 : COD V2 > Product column > product shape isn't look correct
  assets/product-column.css
  sections/product-column.liquid
  styles/product-column.scss
Labels: Ready for review

#57 Featured products > discount banner shape change after update the banner position
  assets/main.css
  sections/featured-products.liquid
  snippets/product-preview.liquid
  styles/main.scss
  templates/index.json
Labels: Ready for review

#58 Multi-columns > UI bugs
  sections/multi-column.liquid
Labels: Ready for review

#55 YSHOP2-420: Section initial background color is not getting applied
  sections/feature-products-by-category.liquid
Labels: enhancement, Ready for review

#60 YSHOP2-421: Dedicated setting for title text color
  sections/feature-products-by-category.liquid
  templates/index.json
Labels: enhancement, Ready for review

#59 Remove "Hide social media" toggle
  sections/main-footer.liquid
Labels: Ready for review

#62 YSHOP2-427: For loading optimization load the video thumbnail first before you load the video
  .github/pull_request_template.md
  assets/video.css
  assets/video.js
  assets/video_default_image.jpeg
  sections/main-video.liquid
  styles/video.scss
Labels: enhancement, Ready for review

#63 YSHOP2-429: COD v2 - Multi-column block description should accept text not html
  sections/multi-column.liquid
Labels: enhancement, Ready for review

#66 YSHOP2-365 : COD V2 > cart page > min height is missing
  assets/cart.js
  assets/main.css
  sections/main-cart.liquid
  styles/main.scss
Labels: Ready for review

#64 YSHOP2-431: keep the same overlay setting for both versions (Desktop & Mobile)
  sections/desktop-slider.liquid
Labels: Ready for review

#65 YSHOP2-432: Add toggle setting to hide the footer section
  sections/main-footer.liquid
Labels: Ready for review

#69 YSHOP2-434: COD v2 - Fix default Columns count
  sections/multi-column.liquid
Labels: enhancement, Ready for review

#71 DARK: fix count range
  templates/index.json
Labels: enhancement, Ready for review

#70 YSHOP2-438: Navbar global setting to be removed
  config/settings_data.json
  config/settings_schema.json
Labels: Ready for review

#68 YSHOP2-436: Option to hide the nav-bar
  sections/main-navbar.liquid
Labels: Ready for review

#74 YSHOP2-442: remove the cart badge from global settings and add it to use the primary color
  config/settings_data.json
  sections/main-navbar.liquid
  snippets/head-config.liquid
Labels: Ready for review

#76 YSHOP2-437 : COD V2 ~ CLONE - Naming conventions, first letter uppercase only
  config/settings_schema.json
  sections/desktop-slider.liquid
  sections/feature-products-by-category.liquid
  sections/featured-collections.liquid
  sections/featured-product-slider.liquid
  sections/featured-products.liquid
  sections/main-express-checkout.liquid
  sections/main-footer.liquid
  sections/main-video.liquid
  sections/multi-column.liquid
  sections/notice-bar.liquid
  sections/product-column.liquid
  sections/product.liquid
Labels: Ready for review

#77 YSHOP2-449: COD v2 - Cart page quantity update issue
  sections/main-cart.liquid
Labels: enhancement, Ready for review

#78 YSHOP2-448: Video section: Title doesn't work
  assets/video.css
  sections/main-video.liquid
  styles/video.scss
Labels: Ready for review

#81 YSHOP2-452: Pagination in mobile will only be displayed if both desktop & mobile pagination toggles are on
  sections/desktop-slider.liquid
Labels: Ready for review

#82 YSHOP2-457 : COD V2 ~ CLONE - We need to hide some sections for all pages except for home & product page
  sections/desktop-slider.liquid
  sections/feature-products-by-category.liquid
  sections/featured-collections.liquid
  sections/featured-product-slider.liquid
  sections/featured-products.liquid
  sections/main-collection.liquid
  sections/main-express-checkout.liquid
  sections/main-video.liquid
  sections/multi-column.liquid
  sections/product-column.liquid
  sections/product-reviews.liquid
  sections/product.liquid
  templates/upsell.json
Labels: Ready for review

#84 YSHOP2-465: "Items and links color" setting not working
  assets/navbar.css
  sections/main-navbar.liquid
  styles/navbar.scss
Labels: enhancement, Ready for review

#86 YSHOP2-455: Font weight: 100-200-300 | 400-500 | 600-700-800-900 are the same weight as well
  sections/desktop-slider.liquid
Labels: Ready for review

#87 YSHOP2-463 : COD V2 ~ CLONE - Express checkout button
  snippets/single-product.liquid
Labels: Ready for review

#89 YSHOP2-468 : COD V2 ~ CLONE - Update order & naming of some settings
  sections/desktop-slider.liquid
  sections/featured-product-slider.liquid
Labels: Ready for review

#91 YSHOP2-469 : COD V2 ~ CLONE - Products Slider > Display countdown even if time runs out
  assets/helper.js
Labels: Ready for review

#92 YSHOP2-467: "Font family" should have a default value
  sections/main-navbar.liquid
Labels: enhancement, Ready for review

#95 YSHOP2-479: COD v2 - The pagination doesn't work on click
  assets/queries-handler.js
  snippets/main-pagination.liquid
Labels: Ready for review

#99 YSHOP2-477: COD v2 - Tag banner doesn't have a style
  sections/product-column.liquid
  snippets/product-home.liquid
  snippets/product-slider.liquid
  snippets/single-product.liquid
Labels: enhancement, Ready for review

#96 YSHOP2-473: COD V2 ~ Products slider section > fix bugs
  sections/featured-product-slider.liquid
  snippets/product-slider.liquid
Labels: Ready for review

#97 YSHOP2-478: COD v2 - The dropdown filter doesn't open on click
  assets/custom-select.js
  assets/product-listing.css
  assets/queries-handler.js
  snippets/custom-select.liquid
  snippets/main-sort.liquid
  styles/product-listing.scss
Labels: enhancement, Ready for review

#103 YSHOP2-500 : Countdown functionality triggering an infinite loop making the web page crush
  assets/helper.js
Labels: enhancement

#104 YSHOP2-491: COD-Theme 2 > Product slider > Fix UI bugs
  sections/featured-product-slider.liquid
  templates/index.json
Labels: Ready for review

#105 YSHOP2-496 : COD V2 > Product column > add missing option
  sections/product-column.liquid
  templates/index.json
Labels: Ready for review

#106 YSHOP2-497: The cart badge need to update with the sdk when the user add to cart
  assets/add-to-cart.js
  assets/cart.js
Labels: Ready for review

#107 YSHOP2-498: When you delete a product from the cart the total number of the products on the cart doesn't update
  assets/cart.css
  assets/cart.js
  assets/collection-listing.css
  sections/main-cart.liquid
  styles/cart.scss
  styles/collection-listing.scss
Labels: Ready for review

#108 YSHOP2-504: When we add a product that has no variants it shouldn’t show in the card drawer as : default: default
  assets/cart-drawer.css
  assets/cart-drawer.js
  styles/cart-drawer.scss
Labels: Ready for review

#110 YSHOP2-505 : Search page > fix UI bugs
  assets/cart.js
  assets/main.js
  locales/ar.default.json
  sections/main-cart.liquid
  sections/main-search.liquid
Labels: Ready for review

#111 YSHOP2-559 : COD V2 > Some sections doesn't have unique CSS class
  assets/helper.js
  assets/main.js
  assets/video.css
  assets/video.js
  assets/video_default_image.jpeg
  sections/desktop-slider.liquid
  sections/feature-products-by-category.liquid
  sections/featured-collections.liquid
  sections/featured-product-slider.liquid
  sections/featured-products.liquid
  sections/main-video.liquid
  sections/multi-column.liquid
  styles/video.scss
  templates/index.json
Labels: Ready for review

#112 YSHOP2-595 : COD v2 > Set the default text colors for some sections
  config/settings_data.json
  sections/featured-products.liquid
  sections/main-footer.liquid
  sections/multi-column.liquid
  templates/index.json
Labels: Ready for review

#113 YSHOP2-596: Default title in the product slider section - Theme 2
  templates/index.json
Labels: Ready for review
