Repository youcan-shop/cod-theme-2, pull requests merged in 2023-03, with the labels that each got.

#3 YSHOP2-147: As a seller, I would like to be able to add one or more slider images
  assets/desktop-slider.css
  assets/dropdown.css
  assets/mobile-slider.css
  sections/desktop-slider.liquid
  snippets/head-config.liquid
  snippets/slider.liquid
  styles/desktop-slider.scss
  styles/mobile-slider.scss
  templates/index.json
Labels: enhancement, Ready for review

#1 YSHOP2-149: As a seller, I want to be able to add a list of products
  assets/featured-products.css
  assets/main.css
  config/settings_data.json
  config/settings_schema.json
  locales/ar.default.json
  locales/en.json
  locales/fr.json
  sections/featured-products.liquid
  snippets/product-preview.liquid
  styles/featured-products.scss
  styles/main.scss
  templates/index.json
Labels: enhancement, Ready for review

#5 YSHOP2-145: As a seller, I would like to be able to add a notice bar
  config/settings_data.json
  config/settings_schema.json
  sections/notice-bar.liquid
Labels: enhancement, Ready for review

#7 YSHOP2-148:As a seller, I would like to be able to add multiple columns
  sections/multi-column.liquid
  templates/index.json
Labels: enhancement

#8 YSHOP2-146 :As a seller, I would like to be able to add and configure the navigation bar
  assets/navbar.css
  config/settings_data.json
  sections/main-navbar.liquid
  snippets/icon.liquid
  styles/navbar.scss
Labels: enhancement

#9 YSHOP2-150: As a seller, I want to be able to add a slider of products
  assets/countdown.css
  assets/desktop-slider.css
  assets/featured-products.css
  assets/product-slider.css
  locales/ar.default.json
  locales/en.json
  locales/fr.json
  sections/desktop-slider.liquid
  sections/featured-product-slider.liquid
  sections/thankyou.liquid
  snippets/countdown.liquid
  snippets/product-slider.liquid
  snippets/slider.liquid
  styles/countdown.scss
  styles/desktop-slider.scss
  styles/featured-products.scss
  styles/product-slider.scss
  templates/index.json
Labels: Ready for review

#10 YSHOP2-151: As a seller, I want to be able to add a list of products from the same category
  assets/featured-products.css
  assets/main.css
  sections/feature-products-by-category.liquid
  styles/featured-products.scss
  styles/main.scss
  templates/index.json
Labels: enhancement

#11 YSHOP2-163: As a seller, I want to be able to add the quantity
  assets/product-quantity-input.js
  assets/product.css
  styles/product.scss
Labels: enhancement, Ready for review

#12 YSHOP2-152: As a seller, I want to be able to add customer reviews
  assets/main.css
  assets/reviews.css
  assets/reviews.js
  snippets/head-config.liquid
  snippets/product-home.liquid
  snippets/reviews.liquid
  styles/main.scss
  styles/reviews.scss
  templates/index.json
Labels: enhancement, Ready for review

#13 DARK: reviews
  assets/reviews.css
  config/settings_data.json
  styles/reviews.scss
Labels: enhancement, Ready for review

#15 YSHOP2-156: As a seller, I want to be able to add a video
  assets/video.css
  sections/main-video.liquid
  styles/video.scss
  templates/index.json
Labels: enhancement, Ready for review

#16 YSHOP2-189: As a buyer, I want to be able to see a recap of my cart items
  assets/cart.css
  assets/main.css
  locales/ar.default.json
  locales/en.json
  locales/fr.json
  sections/main-cart.liquid
  snippets/quantity-input.liquid
  styles/cart.scss
  styles/main.scss
Labels: enhancement, Ready for review

#19 YSHOP2-165: As a seller, I want to be able to add the express checkout
  assets/countdown.css
  assets/express-checkout.css
  assets/featured-products.css
  assets/product-card.css
  assets/product.js
  snippets/express-checkout.liquid
  snippets/product-card.liquid
  snippets/sticky-checkout.liquid
  styles/countdown.scss
  styles/express-checkout.scss
  styles/product-card.scss
  templates/product.json
Labels: enhancement

#21 YSHOP2-158: As a seller, I want to be able to customize the footer
  assets/footer.css
  config/settings_data.json
  sections/featured-collections.liquid
  sections/main-footer.liquid
  styles/footer.scss
Labels: Ready for review

#22 fix: express checkout overflow
  assets/express-checkout.css
  styles/express-checkout.scss
Labels: bug

#23 YSHOP2-193: As a seller, I would like to be able to add the list of all collections in one page
  assets/collection-listing.css
  locales/ar.default.json
  locales/en.json
  locales/fr.json
  sections/main-list-collections.liquid
  snippets/collection-preview.liquid
  styles/collection-listing.scss
Labels: enhancement, Ready for review

#24 YSHOP2-192: As a seller, I would like to be able to add a thank you page after completing a purchase
  assets/main.css
  assets/thankyou.css
  assets/thankyou.png
  locales/ar.default.json
  locales/en.json
  locales/fr.json
  sections/thankyou.liquid
  styles/thankyou.scss
  templates/thankyou.json
Labels: enhancement, Ready for review

#25 YSHOP2-157: As a seller, I want to be able to add a product column section
  assets/product-column.css
  sections/product-column.liquid
  sections/product.liquid
  snippets/product-home.liquid
  styles/product-column.scss
  styles/product.scss
  templates/index.json
Labels: enhancement, Ready for review

#27 YSHOP2-194: As a seller, I would like to be able to add the list of searchable products in one page
  assets/queries-handler.js
  layouts/theme.liquid
  sections/main-search.liquid
Labels: enhancement

#28 Refactor: sections
  assets/collection-listing.css
  assets/components.css
  assets/featured-collections.css
  assets/featured-products-by-category.css
  assets/featured-products.css
  assets/product-listing.css
  assets/product-slider.css
  assets/video.css
  sections/feature-products-by-category.liquid
  sections/featured-collections.liquid
  sections/main-collection.liquid
  sections/main-list-collections.liquid
  snippets/collection-preview.liquid
  snippets/product-preview.liquid
  snippets/product-slider.liquid
  styles/collection-listing.scss
  styles/components.scss
  styles/featured-collections.scss
  styles/featured-products-by-category.scss
  styles/featured-products.scss
  styles/helpers/_mixins.scss
  styles/product-listing.scss
  styles/product-slider.scss
Labels: enhancement
